### ISSUE TITLE
ES 1.0.0

### ISSUE THREAD

**Issue by bstst** [ncolomer/elasticsearch-osmosis-plugin#12]
I'm on ES 1.0.0, and the plugin just keeps on failing with this:

```
INFO: [Angler] failed to get local cluster state for [#transport#-1][inet[/127.0.0.1:9300]], disconnecting...
```

Even though it's a single node cluster, it is up and working, and I tried passing in various options to no avail. I'm running it more or less like this (tried all kinds of options here):

```
osmosis --read-pbf my.osm.pbf --wes cluster.hosts=localhost:9300 cluster.name='elasticsearch_bstst'
```

Is this the ES version which is to blame here?

**Comment by ncolomer** [comment]
Yeah, I did not port this plugin to the new ES 1.x branch... yet :)
I plan to work on this soon! Stay tuned.

**Comment by FrancescElies** [comment]
Hi,

I am also having issues with it is this error related to the issue of using the last elasticsearch version? 

I am using _osmosis-0.43_ and _elasticsearch 1.3.1_

Error:

```
Aug 07, 2014 7:19:56 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.elasticsearch.client.transport.NoNodeAvailableException: No node available
```

Thanks in advance,
Francesc

**Comment by FrancescElies** [comment]
I think I got a bit further, I installed _Elasticsearch 0.90.10_ and _osmosis-0.43_
https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.deb

But I am experimenting another kind of issue

```
INFO: [Rocket Raccoon] failed to get local cluster state for [Dreadknight][kzFvcnmAS12Yvp09f2z9qA][inet[/148.229.156.114:9300]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.state.ClusterStateResponse]
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.state.ClusterStateResponse]
```

I'll keep searching and if I find the solution I will post it
