### ISSUE TITLE
Using lats+lons instead referenced nodes

### ISSUE THREAD

**Issue by karussell** [ncolomer/elasticsearch-osmosis-plugin#3]
Ways are referencing to node ids but it would be of more use to 
1. fetch the node id its associated lat+lon from elasticsearch
2. store this information in the way document as geo_point (or multiple?)

this enables searching for positions of street.

**Comment by ncolomer** [comment]
You're absolutely right, I'll work on it

**Comment by karussell** [comment]
Let me know if you need help or where. I'm currently working on OSM (see my graphhopper project) and ES ... but not on both :)

**Comment by ncolomer** [comment]
Yeah, of course your help is very appreciated :)

And actually, I have a question: do you know if it is possible to index a lat/lon field of objects contained in an array with ES? Say we build ways as following:

``` json
{
    "id": 40849832, 
    "nodes": [
        {"id":343866517,"location":[2.379928,48.6752901]},
        {"id":497017646,"location":[2.3795092,48.675636]},
        {"id":497017647,"location":[2.3795936,48.6755728]}
    ],
    "tags": {
        "name": "Avenue Marc Sangnier", 
        "highway": "residential"
    }
}
```

Is it possible to map the <code>location</code> field of each node object as geo_point? And how query them? 

It would be nice to create a reverse geocoding feature from this!

EDIT: [nested type](http://www.elasticsearch.org/guide/reference/mapping/nested-type.html) and [nested query](http://www.elasticsearch.org/guide/reference/query-dsl/nested-query.html) seem a good way to answer to that need

**Comment by karussell** [comment]
It is possible, have a look: https://gist.github.com/3195115

**Comment by karussell** [comment]
When indexing it is important to only index what is really necessary (e.g. not sure if "nodes:id" is necessary). In order to save resources as OSM files are very heavy.

**Comment by ncolomer** [comment]
Thanks for the helpful gist! So, no need of nested-whatever here, it simply runs ;)

You're absolutely right about nodes:id (and ways:id too): will retrieve them.

Another question: are node/way relations one-to-one? I mean, in terms of data model, is a node related to only one way? In this case, it can make sense to embed each node in its way, including tags? (=> no longer need node indice)

**Comment by karussell** [comment]
> Another question: are node/way relations one-to-one?

not always, otherwise crossroads wouldn't be possible. And there are several nodes not involved in any way relation (e.g. for buildings, POI, platforms etc)

Some side notes:

The problem with such a plugin is that there are several use cases and it is really hard to suit everyones need. And one cannot include all the data - due to the massive amount.

So I think it would help if this plugin is configurable and you provide one default configuration (which you like or need), where one e.g. could look up streets by name (then no nodes are needed), but a ngram tokenizer would be helpful.

Other use cases would be 
- to get streets by lat,lon
- get nearby streets
- get POI (now one would need also none-road related nodes)

There are several optimizations to reduce the data amount. E.g. a winding street is stored with several nodes and one could apply the Ramer–Douglas–Peucker algorithm to reduce the node count.

But there are also several problems like querying a circle which intersects a street but not its end-nodes and so it could be missed. Etc etc

Also you can have a look into Spatial4j for several helpful datastructures and ideas. Spatial4j will be used from lucene in the near future and is already used partially. (+ also have a look into Apache SIS)

**Comment by ncolomer** [comment]
Good point.

Originally, I have built this project to make something very simple and generic like the Xapi API (ie. a very simple osm data accessor tool but on an ES cluster) and run some benchmarks. But it would be a shame to not see the things big!

I agree with you that there is lot of use cases, each one requiring to twist the data model to make search more efficient. Indeed, providing something like "build me a reverse geocoding index from these data" or "build me a POI index from these ones" to users would be great.

I want (and I'll) go this way, but I'll probably need anyone's advice/help in a near future :)

**Comment by apavillet** [comment]
Hello and thanks for the work, I juste wanted to check if you made any progress on this ?

Querying ways right now is quite difficult especially for geo queries (such as bounding boxes), one great thing would be to have the location of the nodes (maybe the centroid ?) as well as the IDs of the nodes.

Let me know if you need any help

**Comment by ncolomer** [comment]
Hi @apavillet and thanks for your interest in this project :)

I am currently working on the perfs branch - take a look at the associated [pull request](https://github.com/ncolomer/elasticsearch-osmosis-plugin/pull/6) - to reduce indexing time. I also do efforts to make the code more readable and ease future IndexBuilder implementations.

About this specific issue, I recently implemented the rg (reverse geocoding) index builder. You can checkout the details in the [README.md](https://github.com/ncolomer/elasticsearch-osmosis-plugin/blob/master/README.md) but in few words, this builds a specialized index in which ways are indexed as linestring using the elasticsearch [Shape](http://www.elasticsearch.org/guide/reference/mapping/geo-shape-type.html) feature. 

Thus, you can query for ways within a bounding box (see [this](https://github.com/ncolomer/elasticsearch-osmosis-plugin/blob/9656053f3c7fd900c9b8aff1e14b5f6f9b8a64ad/src/test/java/org/openstreetmap/osmosis/plugin/elasticsearch/index/rg/RgIndexBuilderITest.java#L73) integration test for a query sample using this feature). You can also find builder's current implementation [here](https://github.com/ncolomer/elasticsearch-osmosis-plugin/blob/9656053f3c7fd900c9b8aff1e14b5f6f9b8a64ad/src/main/java/org/openstreetmap/osmosis/plugin/elasticsearch/index/rg/RgIndexBuilder.java#L61).

If you think this can be improved, or if you have specific use-cases, do not hesitate to explain it further in another issue or even submit a pull-request! All contributions of any kind are welcome (actually, the readme lists some specifically) :)

**Comment by apavillet** [comment]
Hi @ncolomer and thank you, your project is exactly what we were looking for as ES lovers :)

I saw the RG builder and have the index created but unless i'm missing something (which is possible :) ) it doesnt fit our need completely.

The problem here is that if we want to query all the nodes (bakery, police station, etc ..) in an area we wont have some of them (high school for exemple, some historic monuments as well) since they are created as ways without any location but rather as set of nodes associated.

**Comment by apavillet** [comment]
And also i think you dont fetch relations yet right ? Some of them (like subway lines) would have been awesome for us :) Let me know if what i'm saying is not clear or if I can help

**Comment by ncolomer** [comment]
> The problem here is that if we want to query all the nodes (bakery, police station, etc ..) in an area we wont have some of them (high school for exemple, some historic monuments as well) since they are created as ways without any location but rather as set of nodes associated.

Yep you're right as in OSM data, it appears geo features sometimes have a related node that describes it (but actually not included in the way's nodes) and sometimes not.

So what I understand - correct me if I'm wrong - is that you need to geo query for both nodes and ways. The entity index might fit your needs but at this time, ways contain only node ids but not related locations.

A solution to this problem could be to create another way indice with _nodes_ field mapped as a geo_point array. Even if it has side effects (see this [issue](https://github.com/elasticsearch/elasticsearch/issues/1846) and its related [post](https://groups.google.com/forum/?fromgroups=#!topic/elasticsearch/DxIUevwZfOs)), you may thus be able to execute your geo distance filter on node and way indices to get the result you expect.

Actually, the rg index builder already do that (fetch locations from all nodes of a given way) but maps the _nodes_ field as a geo_shape type. Moreover, it uses another index (preventing you to query for both nodes and ways) and the geo_shape type is not compatible with the geo distance filter. 

I think we could simply implement a new index builder that builds another way indice with indexed locations instead of ids. What do you think?

> And also i think you dont fetch relations yet right ? Some of them (like subway lines) would have been awesome for us :)

Right but rest assured, it's my next step on the roadmap: I planned to implement relations and add an index builder that index all administrativ boundaries (thus, given a location, you can retrieve cities, region and country). Subway lines are also a great reason to have relations indexed :)

I don't have lot of time now (I'm working on my own time) but i'll do my best to add these features asap

**Comment by apavillet** [comment]
> I think we could simply implement a new index builder that builds another way indice with indexed locations instead  of ids. What do you think?

That'd be great yes :) Another way would be to calculte a centroid for each way but I dont know if it's even doable on ES (that way we would have a real geo point to work with which could accept geo calculations) 

> Right but rest assured, it's my next step on the roadmap: I planned to implement relations and add an index builder that index all administrativ boundaries (thus, given a location, you can retrieve cities, region and country). Subway lines are also a great reason to have relations indexed :)

Like I said tell me if I can help, unforntunately i'm not that good in Java, have you thought about adding your project to the OSM wiki ? What I like about your project is that for me OSM and ES are really a great combination, much easier and faster than postgresql and some people from the OSM community might want to get involved as well

Cheers !

**Comment by ncolomer** [comment]
> Another way would be to calculte a centroid for each way but I dont know if it's even doable on ES (that way we would have a real geo point to work with which could accept geo calculations)

The centroid is also a nice idea to search for ways as for nodes the way you need. I just made some investigations and yep, I'll be able to compute it just before indexing without too many efforts. Elasticsearch can't do by itself or, well, it can do it just-in-time while querying (via scripting) but this is not very efficient.

> Like I said tell me if I can help, unforntunately i'm not that good in Java

Something that would help me a lot is if you could share some elasticsearch queries that you are executing (or want to execute) on the current indexes. Thus I could make my own tests and code some integration tests. Then I'll probably ask you to beta-test this new indice ;)

I just created the issue #7 to summary our discussion about this new indice. Feel free to answer and comment on this as needed.

> Have you thought about adding your project to the OSM wiki ? What I like about your project is that for me OSM and ES are really a great combination, much easier and faster than postgresql and some people from the OSM community might want to get involved as well

This is exactly what motivated me to create this project!

Indeed, communicate more would be a great opportunity to increase project's popularity... I planned to do it but in a second time. Right now, I need to mature this project a bit more: make the code base stronger and add two index builders including the one we are talking about.

Nonetheless, feel free to star the project and speak about it around you, such contribs are welcomed too!

Cheers ;)

**Comment by apavillet** [comment]
Already starred and I will talk about it ;)

On a different matter I started indexing a whole country and I'm having some performance issue, since queries can take very long. Have you done that already and did you have any issue with speed ?

In the gist you'ill find the kind of query i'm doing, it's also the one that takes a long time on a whole country : https://gist.github.com/apavillet/80640cc9e5304bde9204

**Comment by ncolomer** [comment]
> Already starred and I will talk about it ;)

And thanks for that!

> On a different matter I started indexing a whole country and I'm having some performance issue, since queries can take very long. Have you done that already and did you have any issue with speed ?

Yep, the indexing performance issue is already fixed but is still on the [perfs branch](https://github.com/ncolomer/elasticsearch-osmosis-plugin/pull/6): to give you some figures, I currently index 183Mo of PBF-compressed OSM data (~1,7M docs) in 3 minutes on a 1-node (4CPU + 4Go RAM) ES cluster. I still need to commit some changes on this branch before merging it with master. I'll work on it this weekend :)

About query performance, I also modified the indices' mapping: this should probably improve what you observe. Can you describe your cluster configuration and the response time you get for such query?

**Comment by apavillet** [comment]
For the cluster I tried 5 shards 1 replica, no replica, only 1 shard .. Does not seem to change anything.

I was talking more about the query performance on read, the indexing side is quite fine I think ( but eh if you have something even faster coming that's good :) ). Queries (like the one linked above) can take a lot of time ( up to 3 minutes for the first one, then 3 - 4 seconds once they're cached.

**Comment by ncolomer** [comment]
Implemented, see the [mapping](https://github.com/ncolomer/elasticsearch-osmosis-plugin/wiki/Data-mapping#2-document-model) documentation
