### ISSUE TITLE
Add numbers of shards and replica as parameters for index

### ISSUE THREAD

**Issue by apavillet** [ncolomer/elasticsearch-osmosis-plugin#8]
I believe it's not currently possible to pass parameters such as the number of shards / replica for the created index ( http://www.elasticsearch.org/guide/reference/api/admin-indices-create-index.html ).

Changing this parameter  can sometimes helps with performance.

Thanks

**Comment by apavillet** [comment]
Note that this can be achieved  by creating first the mapping in ES then importing the data, so this feature is not blocking but would be pretty handy.

**Comment by ncolomer** [comment]
Right and actually, this feature is already implemented on the [perfs branch](https://github.com/ncolomer/elasticsearch-osmosis-plugin/pull/6) (well not pushed yet but already there!). Planned for the next release - end of the weekend if all goes well :)
